version: '3'
services:
  # Swagger関連
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: 'swagger-editor'
    ports:
      - '19881:8080'
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: 'swagger-ui'
    ports:
      - 8080:8080
    volumes:
      - ./openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml
