version: '3'
services:
  # https://github.com/openapitools/openapi-generator-cli
  # 定義したスキーマから実際の実装ファイルを生成するものなのでこの記述は必要ないかも？
  # モックサーバー用に必要であればとっておく必要がある
  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./:/app
    # openapi-generator-cliのコマンドを実行している
    # 意味は、
    # generate -g 生成するコードの種類を指定→typescript-axios
    # -i /app/openapi.yml OpenAPI Specificationのyamlファイルを指定
    # -o /app/src/types/typescript-axios 出力する場所を指定
    # typescript-axiosの部分を変えれば生成する言語を変更することができる
    command: generate -g typescript-axios -i /app/openapi.yml -o /app/src/types/typescript-axios
  # https://swagger.io/tools/swagger-ui/
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./openapi.yml:/app/openapi.yml
    environment:
      SWAGGER_JSON: /app/openapi.yml
    ports:
      - 8080:8080
  # https://stoplight.io/p/docs/gh/stoplightio/prism
  mock-api:
    image: stoplight/prism
    volumes:
      - ./openapi.yml:/app/openapi.yml
    ports:
      - 4010:4010
    # -dをつけることでランダムなデータが返ってくる
    command: mock -h 0.0.0.0 -d /app/openapi.yml
